---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
        app.kubernetes.io/name: console
    spec:
      containers:
        - name: console
          image: ubuntu:22.04
          command: ["sh"]
          args:
            - -c
            - echo hello && while :; do sleep 3600; done
