---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    name: demo-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        app.kubernetes.io/name: demo-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: demo
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-default-template: json
        vault.hashicorp.com/agent-inject-secret-demo-secrets.json: /secret/data/kubernetes/demo/credentials

    spec:
      serviceAccountName: default
      containers:
        - name: ubuntu
          image: ubuntu:22.04
          command: ["sh"]
          args:
            - -c
            - find /vault && cat /vault/secrets/demo-secrets.json && while :; do sleep 3600; done
